### ISSUE TITLE
O_DBATTRs and schema_gen

### ISSUE THREAD

**Issue by cortlandstarrett** [xtuml/pyxtuml#1]
I have not looked at the code, but results seem to show that dbattrs do not get fields in the schema.

**Comment by john-tornblom** [comment]
You are correct, derived attributes are intentionality omitted from the schema.
Do you think they should be included? It might be convenient at times, but its duplication of data...

**Comment by cortlandstarrett** [comment]
I think they should be included.
I think most of the time, people will not use derived attributes in
meta-models, but BP currently does.

**Comment by cortlandstarrett** [comment]
Omitting an attribute makes sense when the schema is meant to serve a running program.  In such a case, the derived attribute returns a value when called.  However, the application I am running needs a data base to store and transfer the results between running instantiations of the application.

And if I can have this feature, I will deprecate the archetype based schema generators.  :)

**Comment by cortlandstarrett** [comment]
I did the following and mostly get the results I want:

<pre>
diff --git a/bridgepoint/ooaofooa.py b/bridgepoint/ooaofooa.py
index dbbdf5c..8887a41 100644
--- a/bridgepoint/ooaofooa.py
+++ b/bridgepoint/ooaofooa.py
@@ -3823,7 +3823,8 @@ def mk_class(m, o_obj):
         
     while o_attr:
         ty = get_attribute_type(o_attr)
-        if ty and not one(o_attr).O_BATTR[106].O_DBATTR[107]():
+        #if ty and not one(o_attr).O_BATTR[106].O_DBATTR[107]():
+        if ty:
             attributes.append((o_attr.Name, ty))
         else:
             logger.warning('Omitting unsupported attribute %s.%s ' %
diff --git a/xtuml/model.py b/xtuml/model.py
index 3565936..0c1c39a 100644
--- a/xtuml/model.py
+++ b/xtuml/model.py
@@ -437,7 +437,8 @@ class MetaModel(object):
         # set all attributes with an initial default value
         for name, ty in inst.__a__:
             if name in inst.__d__:
-                value = None
+                #value = None
+                value = self._default_value(ty)
             else:
                 value = self._default_value(ty)
</pre>

**Comment by cortlandstarrett** [comment]
...except that an index entry is output. I will filter that for the moment.
Now I have a fast schema_gen and can toss schema_gen.arc.

Good work!  Thanks.

**Comment by john-tornblom** [comment]
Note that the change in xtuml.model suggested above cause problems with the relate/unrelate functions. ModelException: instance is already related

Ran 172 tests in 6.555s
FAILED (errors=72)

**Comment by cortlandstarrett** [comment]
Yes, and it has a couple of other side effects.  I will look to make a more subtle change or add an option.
