### ISSUE TITLE
updates to prebuilder

### ISSUE THREAD

**Issue by cortlandstarrett** [xtuml/pyxtuml#12]
From a conversation on the xtUML Community hangout:
<pre>
pyxtuml has an OAL parser that replicates the functionality of the BridgePoint prebuilder.  Levi and I have looked at this (again) recently.  It has an advantage in that it does not require BridgePoint or Eclipse or even Java.
I was curious to compare the output of both OAL parsers (BridgePoint prebuilder and pyxtuml).  There are a couple of differences.
The biggest difference is that pyxtuml is emitting ACT_SAB instead of ACT_TAB for actions on transitions.  This is probably a bug and probably easy to fix.
I will report it.
There are a couple of other smaller differences that I am exploring.  But the experience is generally positive and conducive to command line build environments.
pyxtuml does not populate some of the more dubious line and column number information in the VALUE subsystem instances.
</pre>
The ACT_TAB issue will need to be fixed for parsing models having actions on transitions.
Adding set arithmetic support is the next most important change.  This will occur around line 1729 of oal.py.

Here is the analysis note for when set operations were added to OAL.  The note even refers to pyrsl support of set operations in RSL.  Now, the OAL grammar can be updated to allow them in the action language.

https://github.com/xtuml/bridgepoint/blob/master/doc-bridgepoint/notes/5007_set_operations/5007_set_operations_ant.md

**Comment by john-tornblom** [comment]
Unfortunately, there is a lack of unit tests in pyxtuml for actions that interact with e.g. instances, state machines and ports. In particular, the modules [sourcegen.py](https://coveralls.io/builds/24114885/source?filename=bridgepoint/sourcegen.py), [prebuild.py](https://coveralls.io/builds/24114885/source?filename=bridgepoint/prebuild.py), and [oal.py](https://coveralls.io/builds/24114885/source?filename=bridgepoint/oal.py) desperately needs attention from a test engineer (see links for coverage metrics).

Some of these things where testing manually on a few test models available at the time, but as pointed out above, there are missing pieces. Going forward, I believe it is essential to have a test model/set of test models that systematically covers the input space of the prebuilder.

**Comment by cortlandstarrett** [comment]
With the command line nature, some testing could be added pretty easily.  The approach to manual testing I was doing was comparing the output of BridgePoint prebuilder with pyxtuml prebuilder.  First, I wanted to understand the differences.  But if we achieve getting them to match, we can then test them against each other going forward.  It would be easy to supply some 'golden SQL' from models providing substantial coverage.
If I begin using this utility more, I will help add some tests.

**Comment by leviathan747** [comment]
Can this issue now be closed? PR serviced here: https://github.com/xtuml/pyxtuml/pull/13

**Comment by cortlandstarrett** [comment]
It could.  However, I have one more quick check I want to make.  If it is easy to link up S_IRDTs instead of core types in set arithmetic, that would be an improvement.

I will confirm that set arithmetic now parses cleanly.  My test included all of the OAL in mc/model/mcooa, escher and mcshare.

**Comment by leviathan747** [comment]
I recommend you raise a separate issue for the IRDT issue. The two problems you called out originally in this issue have been resolved.

**Comment by cortlandstarrett** [comment]
Closing issue as fixed.  I will raise another on IRDTs if I think it is a good idea to make that change.
