### ISSUE TITLE
Prebuilder struggles with invocations of operations/functions via package reference

### ISSUE THREAD

**Issue by johnrwolfe** [xtuml/pyxtuml#21]
### When a class-based operation is invoked through a package reference, the prebuilder confuses it with a port invocation:
ROR]   File "/home/user/.local/lib/python2.7/site-packages/xtuml/tools.py", line 220, in accept
[ERROR]     r = fn(node, **kwargs)
[ERROR]   File "/home/user/.local/lib/python2.7/site-packages/bridgepoint/prebuild.py", line 1279, in accept_InvocationStatementNode
[ERROR]     self.accept(node.invocation, act_smt=act_smt)
[ERROR]   File "/home/user/.local/lib/python2.7/site-packages/xtuml/tools.py", line 220, in accept
[ERROR]     r = fn(node, **kwargs)
[ERROR]   File "/home/user/.local/lib/python2.7/site-packages/bridgepoint/prebuild.py", line 1291, in accept_ImplicitInvocationNode
[ERROR]     return self.accept_PortInvocationNode(node, act_smt=act_smt)
[ERROR]   File "/home/user/.local/lib/python2.7/site-packages/bridgepoint/prebuild.py", line 1382, in accept_PortInvocationNode
[ERROR]     spr_rep = one(c_ir).C_R[4009].SPR_REP[4500](where(ExecutableProperty_Id=c_ep.Id))
[ERROR] AttributeError: 'NoneType' object has no attribute 'Id'
[ERROR] pyxtuml exited with code 1

### When a function is invoked through a package reference, the prebuilder exits with an assertion error:
[ERROR]   File "/home/user/.local/lib/python2.7/site-packages/xtuml/tools.py", line 220, in accept
[ERROR]     r = fn(node, **kwargs)
[ERROR]   File "/home/user/.local/lib/python2.7/site-packages/bridgepoint/prebuild.py", line 1279, in accept_InvocationStatementNode
[ERROR]     self.accept(node.invocation, act_smt=act_smt)
[ERROR]   File "/home/user/.local/lib/python2.7/site-packages/xtuml/tools.py", line 220, in accept
[ERROR]     r = fn(node, **kwargs)
[ERROR]   File "/home/user/.local/lib/python2.7/site-packages/bridgepoint/prebuild.py", line 1363, in accept_FunctionInvocationNode
[ERROR]     relate(v_val, s_dt, 820)
[ERROR]   File "/home/user/.local/lib/python2.7/site-packages/bridgepoint/prebuild.py", line 43, in relate
[ERROR]     assert xtuml.relate(*args, **kwargs)
[ERROR] AssertionError
[ERROR] pyxtuml exited with code 1

### A simple xtUML model illustrating the issue is attached.
[PkgRefIssues.zip](https://github.com/xtuml/pyxtuml/files/4807112/PkgRefIssues.zip)

**Comment by john-tornblom** [comment]
The OAL language seems to have evolved since the pyxtuml prebuilder was made. An analysis note describing OAL language changes since 2017 would help.

**Comment by johnrwolfe** [comment]
The only recent change to the language that comes to mind involves instance set expressions.  A good reference for OAL expressions is [here](https://github.com/xtuml/bridgepoint/blob/master/src/org.xtuml.bp.doc/Reference/OAL/Expressions/Expressions.md).
For this particular issue, the prebuilder handles the invocations in question properly so long as the invoked function/operation resides within the invoking component.  The issue occurs only when the invoked function/operation is defined outside the invoking component, which requires the invoking component to gain visibility to the invoked function/operation through a package reference (1402, EP_PKGREF).

**Comment by john-tornblom** [comment]
Right. The package reference concept was never considered when the pyxtuml prebuilder was first implemented. I think the OAL parser needs some love for this to be done right. Furthermore, the OAL semantics are not 100% clear to me, hence the request for an analysis note.

For example,
- are keywords like assign supported, e.g., `assign x = PKG::FUNC();`?
- Can an package reference have the same name as a port, and be distinguished via the send keyword, e.g., `send x = Name::Signal();` vs `assign x = Name::Signal();`
- Is the PKG "prefix" optional when accessing functions via a package reference?
- can two EP_PKGREF define different functions with the same key identifier, and be imported into a component? If so, which one takes precedence?

**Comment by cortlandstarrett** [comment]
I will try to provide more information.  But a package reference is never
named in OAL.  Think "file system symbolic link".

**Comment by johnrwolfe** [comment]
As Cort indicated, a package name never appears in action language.  Perhaps this image of the test model will help.  If we move the "wrapper" package inside the "test" component and change nothing else, the pre-builder works correctly.
![image](https://user-images.githubusercontent.com/2199907/85324784-49c95900-b47f-11ea-9bcb-54a2b97787ae.png)

**Comment by john-tornblom** [comment]
Ah, right. I was confused by the many occurrences of the identifier "wrapper". Please try this one:

`python -m pip install git+https://github.com/xtuml/pyxtuml.git@prebuild-with-package-references`

The pyxtuml prebuilder assumes the model is complete without syntax errors, hence error reporting on such issues is mostly missing. One of the tracebacks you provided above should say "unknown identifier 'LOG'" or something, since the LOG EE is not in the model.

**Comment by johnrwolfe** [comment]
This version produces identical symptoms to the previous one.
Regarding "...model is complete..." and "...LOG EE is not in the model," LOG EE (and all the other built-in EEs) are provided by the Ciera runtime.  To keep the editor happy, we import the Ciera runtime as a separate project in the workspace, and since the runtime project has IPRs enabled, the application models have visibility of the built-in EEs residing in that project.

**Comment by john-tornblom** [comment]
When I import the attached PkgRefIssues.zip into an empty workspace and parse all activities, I get the following error:
   "Cannot find specified class,  external entity or interface ->LOG<-."

Adding built-in EEs to wrapper package in the wrapper project solves the dependency error in the bridgepoint IDE,
and pyxtuml prebuilder works fine for me (branch prebuild-with-package-references, ofc).

If you still get an error, please reproduce it in a new sample model and share it here.
Oh, and make sure you uninstall pyxtuml, then install with the command line provided above.

**Comment by johnrwolfe** [comment]
It seems this is likely user-error on my part, so please accept my apologies for the trouble.  When I tried this branch a couple days ago, I did not first uninstall pyxtuml before installing the prebuild-with-package-references branch.  Today, I did uninstall it with `pip uninstall pyxtuml` before installing with the command provided above.  Then, I built a new model and reproduced the same symptoms.  I _think_ I have verified that the updated version is installed:
```
user@ubuntu:~/.local/lib/python2.7/site-packages/bridgepoint$ grep PKGREF *.py
ooaofooa.py:    Determine if a PE_PE is contained within a EP_PKG, EP_PKGREF, or a C_C.
schema.py:CREATE TABLE EP_PKGREF (
schema.py:CREATE ROP REF_ID R1402 FROM 1C EP_PKGREF (Referring_Package_ID) PHRASE 'is referenced by' TO 1 EP_PKG (Package_ID) PHRASE 'refers to';
schema.py:CREATE ROP REF_ID R1402 FROM MC EP_PKGREF (Referred_Package_ID) PHRASE 'refers to' TO 1 EP_PKG (Package_ID) PHRASE 'is referenced by';
schema.py:CREATE UNIQUE INDEX I1 ON EP_PKGREF (Referring_Package_ID);
```
But, I do not know how to verify that this version is actually the one executing, as `python -m bridgepoint.pyxtuml --version` produces:  `pyxtuml v2.2.1 (2020-03-12)`.
The attached model is simpler than the original (sorry about that first one) and does not require any EEs.  On my installation, this model produces the same symptoms as the previous model:
```
[ERROR] Traceback (most recent call last):
[ERROR]   File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
[ERROR]     "__main__", fname, loader, pkg_name)
[ERROR]   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
[ERROR]     exec code in run_globals
[ERROR]   File "/home/user/.local/lib/python2.7/site-packages/bridgepoint/prebuild.py", line 1933, in <module>
[ERROR]     main()
[ERROR]   File "/home/user/.local/lib/python2.7/site-packages/bridgepoint/prebuild.py", line 1927, in main
[ERROR]     prebuild_model(m)
[ERROR]   File "/home/user/.local/lib/python2.7/site-packages/bridgepoint/prebuild.py", line 1892, in prebuild_model
[ERROR]     prebuild_action(inst)
[ERROR]   File "/home/user/.local/lib/python2.7/site-packages/bridgepoint/prebuild.py", line 1870, in prebuild_action
[ERROR]     return walker.accept(root)
[ERROR]   File "/home/user/.local/lib/python2.7/site-packages/xtuml/tools.py", line 220, in accept
[ERROR]     r = fn(node, **kwargs)
[ERROR]   File "/home/user/.local/lib/python2.7/site-packages/bridgepoint/prebuild.py", line 1536, in accept_BodyNode
[ERROR]     return ActionPrebuilder.accept_BodyNode(self, node)
[ERROR]   File "/home/user/.local/lib/python2.7/site-packages/bridgepoint/prebuild.py", line 439, in accept_BodyNode
[ERROR]     self.accept(node.block.statement_list)
[ERROR]   File "/home/user/.local/lib/python2.7/site-packages/xtuml/tools.py", line 220, in accept
[ERROR]     r = fn(node, **kwargs)
[ERROR]   File "/home/user/.local/lib/python2.7/site-packages/bridgepoint/prebuild.py", line 458, in accept_StatementListNode
[ERROR]     act_smt = self.accept(child)
[ERROR]   File "/home/user/.local/lib/python2.7/site-packages/xtuml/tools.py", line 220, in accept
[ERROR]     r = fn(node, **kwargs)
[ERROR]   File "/home/user/.local/lib/python2.7/site-packages/bridgepoint/prebuild.py", line 1279, in accept_InvocationStatementNode
[ERROR]     self.accept(node.invocation, act_smt=act_smt)
[ERROR]   File "/home/user/.local/lib/python2.7/site-packages/xtuml/tools.py", line 220, in accept
[ERROR]     r = fn(node, **kwargs)
[ERROR]   File "/home/user/.local/lib/python2.7/site-packages/bridgepoint/prebuild.py", line 1363, in accept_FunctionInvocationNode
[ERROR]     relate(v_val, s_dt, 820)
[ERROR]   File "/home/user/.local/lib/python2.7/site-packages/bridgepoint/prebuild.py", line 43, in relate
[ERROR]     assert xtuml.relate(*args, **kwargs)
[ERROR] AssertionError
[ERROR] pyxtuml exited with code 1
```
[PkgRefIssues2.zip](https://github.com/xtuml/pyxtuml/files/4839713/PkgRefIssues2.zip)

**Comment by john-tornblom** [comment]
The attached zip file works fine for me. It looks like you have the most recent version, but try appending the --upgrade flag.

```console
$ python2 -m pip install --user --upgrade git+https://github.com/xtuml/pyxtuml.git@prebuild-with-package-references
$ python2 -m bridgepoint.prebuild PkgRefIssues2.zip -o /dev/stdout
INSERT INTO ACT_FNB VALUES (
    "91ccbf7c-e7de-4e75-a6bd-744a0d752064", -- Action_ID : UNIQUE_ID
    "857a5175-fdc1-423a-a901-d778bf96bfb2" -- Sync_ID : UNIQUE_ID
);
...
```

Also, your command line argument is not included in the filed issue, which could contain the root of your problems.

**Comment by johnrwolfe** [comment]
I uninstalled pyxtuml and then installed the update with the command provided above:
`python2 -m pip install --user --upgrade git+https://github.com/xtuml/pyxtuml.git@prebuild-with-package-references`.
I have tried two approaches for invoking the prebuilder:  via the Maven-based build system for [Ciera](https://github.com/xtuml/ciera/wiki/Jump_Start) and directly from the command line with:  
`python2 -m bridgepoint.prebuild ./models -o /dev/stdout`.  
Both approaches produce the same output:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/user/.local/lib/python2.7/site-packages/bridgepoint/prebuild.py", line 1933, in <module>
    main()
  File "/home/user/.local/lib/python2.7/site-packages/bridgepoint/prebuild.py", line 1927, in main
    prebuild_model(m)
  File "/home/user/.local/lib/python2.7/site-packages/bridgepoint/prebuild.py", line 1892, in prebuild_model
    prebuild_action(inst)
  File "/home/user/.local/lib/python2.7/site-packages/bridgepoint/prebuild.py", line 1870, in prebuild_action
    return walker.accept(root)
  File "/home/user/.local/lib/python2.7/site-packages/xtuml/tools.py", line 220, in accept
    r = fn(node, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/bridgepoint/prebuild.py", line 1536, in accept_BodyNode
    return ActionPrebuilder.accept_BodyNode(self, node)
  File "/home/user/.local/lib/python2.7/site-packages/bridgepoint/prebuild.py", line 439, in accept_BodyNode
    self.accept(node.block.statement_list)
  File "/home/user/.local/lib/python2.7/site-packages/xtuml/tools.py", line 220, in accept
    r = fn(node, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/bridgepoint/prebuild.py", line 458, in accept_StatementListNode
    act_smt = self.accept(child)
  File "/home/user/.local/lib/python2.7/site-packages/xtuml/tools.py", line 220, in accept
    r = fn(node, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/bridgepoint/prebuild.py", line 1279, in accept_InvocationStatementNode
    self.accept(node.invocation, act_smt=act_smt)
  File "/home/user/.local/lib/python2.7/site-packages/xtuml/tools.py", line 220, in accept
    r = fn(node, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/bridgepoint/prebuild.py", line 1363, in accept_FunctionInvocationNode
    relate(v_val, s_dt, 820)
  File "/home/user/.local/lib/python2.7/site-packages/bridgepoint/prebuild.py", line 43, in relate
    assert xtuml.relate(*args, **kwargs)
AssertionError
```
Please let me know if I can provide more information. 
One data point comes to mind:  I had no trouble updating pyxtuml and successfully retesting the fix for qualified constant names in this same environment, but that fix was delivered on the master branch.

**Comment by john-tornblom** [comment]
Did you try to to run the same command line as I used, i.e., python2 -m bridgepoint.prebuild PkgRefIssues2.zip -o /dev/stdout

**Comment by johnrwolfe** [comment]
I tried that just now, and it worked fine.  So, all this time, I have been invoking the prebuilder incorrectly for this particular model.  I need to slightly restructure my Ciera project, and then it should work fine.  Apologies for the hassle.  Thanks for providing the fix so rapidly.
