### ISSUE TITLE
Transient arrays are not supported?

### ISSUE THREAD

**Issue by johnrwolfe** [xtuml/pyxtuml#24]
Statements of the form:
Labels[index] = "";
Labels[index] = spec.Label;
produce:
ERROR:bridgepoint.prebuild:Unable to evaluate constant expression (V_TVL)

**Comment by john-tornblom** [comment]
What is index, another transient? Try to use a constant expression instead, e.g., Labels[10] = "";

**Comment by johnrwolfe** [comment]
It's been long enough that I've forgotten the exact form of the activity that produced the failure, so I experimented with it a bit today.
1. As you suggest, a constant works just fine for declaring the transient array:  Labels[10] = "";  Once declared, the array can then be used within the activity, so this is a reasonable work-around, though one that Verifier does not require.
2. Using a transient as the index precipitates the pre-builder error.  It's likely we were using a loop, incrementing the transient index, to populate the transient array so that it could then be passed out of the component.
3. Using a parameter or an attribute also precipitates the error.

**Comment by john-tornblom** [comment]
Okey, closing this issue. 

If this is still a problem, reopen this issue along with a proper test case, preferably expressed as other pyxtuml test cases, e.g., tests/test_bridgepoint/test_assign.py.
