### ISSUE TITLE
Duplicate association numbers in different components fail to compile.

### ISSUE THREAD

**Issue by amullarney** [xtuml/pyxtuml#30]
A test case demonstrating this available at:
https://github.com/amullarney/AdHocTests/tree/12006_relate.
This is also: https://support.onefact.net/issues/12006. 
Observations in the discussion of that issue appear to implicate pyxtuml.

**Comment by john-tornblom** [comment]
This is addressed by 85cd66e, please confirm. For future correspondence, be aware that I cannot access https://support.onefact.net/issues/12006 (403 error).

**Comment by amullarney** [comment]
Sorry, problem still exists.

**Comment by amullarney** [comment]
Inadvertently closed...

**Comment by john-tornblom** [comment]
Okey, I need more information regarding expected output to pinpoint the error. I am unsure how to use your model compiler...

**Comment by john-tornblom** [comment]
Could you provide ground truth using the bridgepoint prebuilder?

**Comment by amullarney** [comment]
Not sure what you mean by 'ground truth'. The following is an comment from onefact issue discussion:
This looks like a pyxtuml pre-builder issue.
The incorrectly translated statement:
relate f to b across R7.'phrase2';
resides in Foo/Fred::T1
In the SQL produced by the pre-builder, the id for this statement is: f48bcd02-5372-4b3b-86c1-8f82a7009c2d,
and the referenced relationship id in the relevant instance of ACT_REL is: 685b5061-66eb-4f56-bd42-5eb33ba689c4,
but this is the relationship ID for the Sup/Sub association in the other component, Test,
that just happens to have the same association number, R7, as the simple association
in the Foo component.
The correct relationship id for this statement should be: cc14f00a-1cf0-4327-919b-ba190c8a0011, and
it is never used in any action instances.

If you have Ciera installed, then run 'mvn clean install' on the project.
If you want to share screens with Skype, I can do that...

**Comment by amullarney** [comment]
I can see in Tests.sql - which is input to Ciera - that, while two different instances of R! exist in two different components in the model, only one instance of ACT_REL_VALUES is present in the SQL file. There are two instances of R-REL-VALUES, each with attribute Numb = 1.

**Comment by john-tornblom** [comment]
Okey. In the test model you provided, there are two R_REL instances:

Widgets.xtuml: 76a3a4d4-4435-4aeb-93c4-dced55a9ffbf
Things.xtuml:  bafa727f-8cd5-4784-93a8-4b92d68dd849

With running the following on current master:
`PYTHONPATH=. python -m bridgepoint.prebuild /tmp/AdHocTests/ -o AdHocTests.sql`

I get to folowing relate statement:
```sql
INSERT INTO ACT_REL VALUES (
    "962e0be0-a680-48b9-8ff6-916746b4ee90", -- Statement_ID : UNIQUE_ID
    "f80bd324-551d-40ca-b3c0-846c6111dd09", -- One_Side_Var_ID : UNIQUE_ID
    "a7bc402e-0b1a-41a8-841c-bc09ef7b1bde", -- Other_Side_Var_ID : UNIQUE_ID
    '''is on''', -- relationship_phrase : STRING
    "76a3a4d4-4435-4aeb-93c4-dced55a9ffbf", -- Rel_ID : UNIQUE_ID
    0, -- associationNumberLineNumber : INTEGER
    0, -- associationNumberColumn : INTEGER
    0, -- associationPhraseLineNumber : INTEGER
    0 -- associationPhraseColumn : INTEGER
);
```
I believe this is correct, no? If you get a different behavior, are you sure you are using current master?

**Comment by amullarney** [comment]
This is correct: my previous message was misleading. There is only one 'relate' statement for R1 in the model - but there are two instances of R1 in two different components.
  this:
select any menu from instances of Menu;
select any item from instances of Item;
relate item to menu across R1.'is on';
  compiles as:
    public void UpdateMenu() throws XtumlException {
        Menu menu = context().Menu_instances().any();
        Item item = context().Item_instances().any();
        context().relate_( menu, item );
    }
The relate_ is incomplete: by changing the other R1 to R2 and recompiling:
        context().relate_R1_Item_is_on_Menu( item, menu );

**Comment by john-tornblom** [comment]
@leviathan747 how is pyxtuml integrated with this model compiler? Can you confirm if this is still an issue in current master, I am unable to reproduce the fault.

**Comment by amullarney** [comment]
Apologies. My pyxtuml update apparently did not work - still running with python 2.7.
When I hand edited my installed pyxtuml with your 1-line change my test case compiles - and the SQL is now correct.
I am working on python upgrade and will repeat pyxtuml upgrade.
At that time I will close the issue - unless you want to do so now.

**Comment by john-tornblom** [comment]
Ah, great!

Let's keep the issue open until you or someone else can confirm that it is fixed.

**Comment by amullarney** [comment]
Verified pyxtuml pip update using python 3.8.5. Test case now passes.
