### ISSUE TITLE
Pyxtuml fails when a derived attribute is specified in a package-referenced class.

### ISSUE THREAD

**Issue by amullarney** [xtuml/pyxtuml#37]
[ERROR]   File "/home/amullarney/.local/lib/python3.8/site-packages/bridgepoint/prebuild.py", line 1740, in label
[ERROR]     return '::'.join([self.c_c.Name, self._o_obj.Name, o_attr.Name])
[ERROR] AttributeError: 'NoneType' object has no attribute 'Name'
[ERROR] pyxtuml exited with code 1

**Comment by amullarney** [comment]
Test case at: https://github.com/amullarney/CieraTest/tree/37_pyxtuml_derived_attribute

**Comment by leviathan747** [comment]
Resolved by #33
