### ISSUE TITLE
pyxtuml allows creation of duplicate associations

### ISSUE THREAD

**Issue by lwriemen** [xtuml/pyxtuml#44]
The pyxtuml defines Association as "connects two metaclasses to each other via two directed links." The define_association function will create both links, but doesn't check to see if the Association was previously defined.

An example of this can be found in the pyrsl test, test_relate_using. In this test, Association R1 is created twice using a reversed source_phrase and target_phrase in the second creation of R1. The second creation of R1 should be unnecessary, because the two links are created in the first creation of R1.

The use of "source" and "target" in the parameter names is probably confusing in the usage of define_association, because the association should be non-directional.

If the creation of duplicate Associations is required, then this is probably a bigger issue.

**Comment by lwriemen** [comment]
After running the pyrsl tests, it appears this is by design, but I'm confused as to why this duplication would be necessary. It now appears that Association and Link are redundant.

**Comment by john-tornblom** [comment]
I believe the motivation originate from cases with reflexive relations with an association class.

**Comment by leviathan747** [comment]
Closing this issue.

**Comment by lwriemen** [comment]
> I believe the motivation originate from cases with reflexive relations with an association class.

I can see how it's being used, I just don't understand why it's necessary when you already have a link in both directions.
